//
// LISTA DE CLAVE VALOR QUE DETECTA DE QUE ARCHIVO ES CADA TECNOLOGIA
//
export const techRules = {
  exact: {
    "package.json": "Node.js",
    "requirements.txt": "Python",
    "pom.xml": "Java",
    "index.html": "Frontend",
    "Cargo.toml": "Rust",
    "go.mod": "Go",
    "Gemfile": "Ruby",
    "Gemfile.lock": "Ruby",
    "Rakefile": "Ruby",
    "*.gemspec": "Ruby",
  },

  extensions: {
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".css": "CSS",
    ".html": "HTML",
    ".sql": "SQL",
    ".py": "Python",
    ".pyw": "Python",
    ".php": "PHP",
    ".cs": "C#",
    ".csproj": "C#",
    ".sln": "C#",
    ".xaml": "C#",
    ".rs": "Rust",
    ".java": "Java",
    ".go": "Go",
    ".c": "C",
    ".h": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".rb": "Ruby",
    ".rake": "Ruby",
    ".gemspec": "Ruby",
    ".ini": "INI",
    ".cfg": "INI",
  },
};
