export const fileTypes = {
  ".js": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".jsx": "javascript",
  ".ts": "typescript",
  ".tsx": "typescript",
  ".css": "stylesheet",
  ".json": "data",
  ".html": "markup",
  ".sql": "sql",
  ".py": "python",
  ".pyw": "python",
  ".php": "php",
  ".cs": "csharp",
  ".sln": "sln",
  ".csproj": "csproj",
  ".config": "config",
  ".xaml": "xaml",
  ".rs": "rust",
  ".java": "java",
  ".go": "go",
  ".c": "c",
  ".h": "c",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".cxx": "cpp",
};
